In [7]:
import pandas as pd

# Load the CSV file
df = pd.read_csv("./backup_stats_31102024.csv")  # Replace with your CSV file path

# Assuming 'submission_date' is in a valid date format (e.g., 'YYYY-MM-DD' or 'MM/DD/YYYY')
# Convert 'submission_date' to datetime
df['submission_date'] = pd.to_datetime(df['submission_date'], errors='coerce')

# Split 'submission_date' into separate 'day', 'month', and 'year' columns
df['day'] = df['submission_date'].dt.day
df['month'] = df['submission_date'].dt.month
df['year'] = df['submission_date'].dt.year

# Filter to keep only rows where the month is July (7), August (8), or September (9)
df_filtered = df[df['month'].isin([7, 8, 9])]

# # Further filter to keep only rows where the day is between 25 and 31
# df_filtered = df_filtered[(df_filtered['day'] >= 25) & (df_filtered['day'] <= 31)]


# Group by 'site_id', 'month', and 'year', and return the maximum 'day'
grouped_df = df_filtered.groupby(['site_id', 'month', 'year'], as_index=False).agg({'day': 'max'})

# Create new columns for July, August, and September based on month and submission_date range (25-31)
grouped_df['July'] = grouped_df.apply(lambda x: 1 if x['month'] == 7 and 25 <= x['day'] <= 31 else 0, axis=1)
grouped_df['August'] = grouped_df.apply(lambda x: 1 if x['month'] == 8 and 25 <= x['day'] <= 31 else 0, axis=1)
grouped_df['September'] = grouped_df.apply(lambda x: 1 if x['month'] == 9 and 25 <= x['day'] <= 31 else 0, axis=1)

# Select only the desired columns
output_df = grouped_df[['site_id', 'July', 'August', 'September']]
output_df
# Save the output to a new Excel file
output_file_path = 'f_backup.csv'  # Replace with your desired output file path
output_df.to_csv(output_file_path, index=False)

print("Processed data saved to:", output_file_path)

Processed data saved to: f_backup.csv

In [8]:
df

,id,month,year,backup_date,no_of_records,referrence,site_id,status,submission_date,day
0,00031eab-d931-49c7-85e5-24d1f94d10d0,7,2024,2024-07-17,13999,8f0e9acc-3e53-4908-b4f8-850834db6114,ZW02050B,COMPLETED,2024-07-17 00:00:00,17
1,00034632-b5cc-4597-bfa0-eb3a1a8e21c7,10,2024,2024-10-17,50000,c4fff024-6488-4c0e-9ac7-98527471ac24,ZW05020A,COMPLETED,2024-10-17 23:30:37,17
2,00061250-47fc-4bd1-b7bf-533bc45612d6,7,2024,2024-07-06,50000,a6784dcc-4640-443c-9cc1-6b47341228d6,ZW060507,COMPLETED,2024-07-06 00:00:00,6
3,00061673-b4a9-4984-bb62-d724008e83a5,3,2024,2024-03-03,4361,116aca4e-2cf2-4b7b-b24a-60a530fc81ba,ZW010434,COMPLETED,2024-03-03 00:00:00,3
4,0006d026-6811-4436-83c4-a443fe99a098,8,2024,2024-08-08,4542,80940327-18a3-41b5-8d8f-1363d519e6bb,ZW060628,COMPLETED,2024-08-08 00:00:00,8
...,...,...,...,...,...,...,...,...,...,...
47826,fff9ea41-24d9-4a41-8c8d-2606928efeff,10,2024,2024-10-11,1909,793fd5ce-0429-4ce8-bc1c-c8f37e35bfd2,ZW000A19,COMPLETED,2024-10-11 14:49:13,11
47827,fffa6218-98d6-4b35-bfb3-d23d3ec1f5bb,5,2024,2024-05-21,2369,c0d59c3d-fecd-48ba-a7c3-c80e8e684f91,ZW07030A,COMPLETED,2024-05-21 00:00:00,21
47828,fffa7de6-b689-4f64-925d-c53bdf741501,7,2024,2024-07-03,50000,9b22acc7-8e02-4c34-a338-4af639645526,ZW010521,COMPLETED,2024-07-03 00:00:00,3
47829,fffd4431-ab77-4c3d-a648-63741f02a1fc,9,2024,2024-09-02,1263,f36912de-fd28-4bcb-9ac9-02b296e02ec5,ZW08020B,COMPLETED,2024-09-02 00:00:00,2
47830,fffdaf82-42a4-47c6-b8ea-d8dc3f9b0443,10,2024,2024-09-06,3508,9d176313-a46d-4d4e-97d8-072c3ac45875,ZW040461,COMPLETED,2024-10-08 22:42:43,8

In [9]:
# Count duplicates based on 'site_id'
duplicate_counts_by_site = df.groupby('site_id').size()
duplicates = duplicate_counts_by_site[duplicate_counts_by_site > 1]
print("Duplicate counts by 'site_id':")
print(duplicates)

Duplicate counts by 'site_id':
site_id
ZW000A01    426
ZW000A02     53
ZW000A05     49
ZW000A07      6
ZW000A08     27
           ...
ZW090A35    296
ZW090A49    247
ZW090A65      7
ZW090A66    107
ZW70601       7
Length: 646, dtype: int64

In [10]:
df= pd.read_csv("./f_backup.csv")
df['site_id'].duplicated()

0      False
1      False
2       True
3       True
4      False
       ...
867    False
868    False
869     True
870     True
871    False
Name: site_id, Length: 872, dtype: bool

In [11]:
import pandas as pd

# Load the CSV file
df = pd.read_csv("./backup_stats_31102024.csv")  # Replace with your CSV file path

# Print the first few rows of df
print(df.head())

# Convert 'submission_date' to datetime
df['submission_date'] = pd.to_datetime(df['submission_date'], errors='coerce')

# Split 'submission_date' into separate 'day', 'month', and 'year' columns
df['day'] = df['submission_date'].dt.day
df['month'] = df['submission_date'].dt.month
df['year'] = df['submission_date'].dt.year

# Filter to keep only rows where the month is July (7), August (8), or September (9)
df_filtered = df[df['month'].isin([7, 8, 9])]

# Further filter to keep only rows where the day is between 25 and 31
df_filtered = df_filtered[(df_filtered['day'] >= 25) & (df_filtered['day'] <= 31)]

# Group by 'site_id', 'month', and 'year', and return the maximum 'day'
grouped_df = df_filtered.groupby(['site_id', 'month', 'year'], as_index=False).agg({'day': 'max'})

# Create new columns for July, August, and September based on month and submission_date range (25-31)
grouped_df['July'] = grouped_df.apply(lambda x: 1 if x['month'] == 7 else 0, axis=1)
grouped_df['August'] = grouped_df.apply(lambda x: 1 if x['month'] == 8 else 0, axis=1)
grouped_df['September'] = grouped_df.apply(lambda x: 1 if x['month'] == 9 else 0, axis=1)

# Pivot the DataFrame to make sure all site_id rows are present, even if the values are zero
output_df = (
    grouped_df.pivot_table(index='site_id', values=['July', 'August', 'September'], aggfunc='max', fill_value=0)
    .reset_index()
)

# Save the output to a new CSV file
output_file_path = 'f_backup.csv'  # Replace with your desired output file path
output_df.to_csv(output_file_path, index=False)

print("Processed data saved to:", output_file_path)
output_df

print(df.shape)

                                     id  month  year backup_date  \
0  00031eab-d931-49c7-85e5-24d1f94d10d0      7  2024  2024-07-17
1  00034632-b5cc-4597-bfa0-eb3a1a8e21c7     10  2024  2024-10-17
2  00061250-47fc-4bd1-b7bf-533bc45612d6      7  2024  2024-07-06
3  00061673-b4a9-4984-bb62-d724008e83a5      3  2024  2024-03-03
4  0006d026-6811-4436-83c4-a443fe99a098      8  2024  2024-08-08

   no_of_records                            referrence   site_id     status  \
0          13999  8f0e9acc-3e53-4908-b4f8-850834db6114  ZW02050B  COMPLETED
1          50000  c4fff024-6488-4c0e-9ac7-98527471ac24  ZW05020A  COMPLETED
2          50000  a6784dcc-4640-443c-9cc1-6b47341228d6  ZW060507  COMPLETED
3           4361  116aca4e-2cf2-4b7b-b24a-60a530fc81ba  ZW010434  COMPLETED
4           4542  80940327-18a3-41b5-8d8f-1363d519e6bb  ZW060628  COMPLETED

       submission_date
0  2024-07-17 00:00:00
1  2024-10-17 23:30:37
2  2024-07-06 00:00:00
3  2024-03-03 00:00:00
4  2024-08-08 00:00:00
Processed data saved to: f_backup.csv
(47831, 10)

In [12]:
df= pd.read_csv("./f_backup.csv")
df
print(df.shape)

df_pro = pd.read_csv("./Facility Registry v3.csv")
df_pro
print(df_pro.shape)

(219, 4)
(995, 19)

In [13]:
df2_selected = df_pro[['Province', 'District', 'Facility ID', 'Facility']]

In [14]:
merged_df = pd.merge(df, df2_selected, left_on="site_id", right_on="Facility ID", how="inner")
merged_df

,site_id,August,July,September,Province,District,Facility ID,Facility
0,ZW000A01,1,0,1,Harare,ha North Western District,ZW000A01,ha Avondale Clinic
1,ZW000A0D,1,1,0,Harare,ha Western District,ZW000A0D,Wilkins Infectious Disease Hospital
2,ZW000A17,1,0,0,Harare,ha Northern District,ZW000A17,ha Hatcliffe PolyClinic
3,ZW000A18,0,1,0,Harare,ha South Western District,ZW000A18,ha Highfield PolyClinic
4,ZW000A21,0,0,1,Harare,ha North Western District,ZW000A21,ha Mabelreign Satellite Clinic
...,...,...,...,...,...,...,...,...
211,ZW090A14,0,0,1,Bulawayo,Nkulumane,ZW090A14,Dr Shennan Clinic
212,ZW090A17,1,0,0,Bulawayo,Nkulumane,ZW090A17,Nketa Clinic
213,ZW090A33,1,1,0,Bulawayo,Nkulumane,ZW090A33,Maqhawe Clinic
214,ZW090A49,1,1,1,Bulawayo,Northern Surbubs,ZW090A49,Ceshhar Clinic
215,ZW090A66,1,1,0,Bulawayo,Northern Surbubs,ZW090A66,Mahatshula Private Clinic

In [15]:
merged_df.drop('Facility ID', axis=1, inplace=True)
merged_df

,site_id,August,July,September,Province,District,Facility
0,ZW000A01,1,0,1,Harare,ha North Western District,ha Avondale Clinic
1,ZW000A0D,1,1,0,Harare,ha Western District,Wilkins Infectious Disease Hospital
2,ZW000A17,1,0,0,Harare,ha Northern District,ha Hatcliffe PolyClinic
3,ZW000A18,0,1,0,Harare,ha South Western District,ha Highfield PolyClinic
4,ZW000A21,0,0,1,Harare,ha North Western District,ha Mabelreign Satellite Clinic
...,...,...,...,...,...,...,...
211,ZW090A14,0,0,1,Bulawayo,Nkulumane,Dr Shennan Clinic
212,ZW090A17,1,0,0,Bulawayo,Nkulumane,Nketa Clinic
213,ZW090A33,1,1,0,Bulawayo,Nkulumane,Maqhawe Clinic
214,ZW090A49,1,1,1,Bulawayo,Northern Surbubs,Ceshhar Clinic
215,ZW090A66,1,1,0,Bulawayo,Northern Surbubs,Mahatshula Private Clinic

In [16]:
# Save the output to a new CSV file
output_file_path = 'f_backup_final.csv'  # Replace with your desired output file path
merged_df.to_csv(output_file_path, index=False)